In [6]:
import tensorflow as tf

In [7]:
print(('Your TensorFlow Version: {0}').format(tf.__version__))

Your TensorFlow Version: 2.12.0


In [ ]:
#Create a variable tensor V
V = tf.Variable([[3,1],
                 [5,2]])
print(V)

In [8]:
import tensorflow as tf

# Create the first constant tensor A
A = tf.constant([[1, 2], [3, 4]])

# Create the second constant tensor B
B = tf.constant([[7, 8], [4, 5]])

# Concatenate the tensors along the specified axis (axis=1 in this case)
AB = tf.concat(values=[A, B], axis=1)

# Print the concatenated tensor values
print(AB.numpy())


[[1 2 7 8]
 [3 4 4 5]]


In [10]:
tensor = tf.zeros (shape = [3,4], dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [11]:
tensor = tf.zeros (shape = [3,4], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [12]:
tensor = tf.ones (shape = [3,4], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [13]:
tensor = tf.ones (shape = [3,4], dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [15]:
reshaped_tensor = tf.reshape(tensor = tensor, shape = [4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

In [17]:
tesnor2 = tf.random.uniform(shape=[3,4], dtype= tf.float32)
tesnor2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.5051116 , 0.74632716, 0.59649336, 0.12865353],
       [0.16348207, 0.32885623, 0.81697214, 0.7847177 ],
       [0.2846552 , 0.85058534, 0.06352842, 0.18349874]], dtype=float32)>

In [18]:
reshaped_tensor = tf.reshape(tensor = tesnor2, shape = [4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.5051116 , 0.74632716, 0.59649336],
       [0.12865353, 0.16348207, 0.32885623],
       [0.81697214, 0.7847177 , 0.2846552 ],
       [0.85058534, 0.06352842, 0.18349874]], dtype=float32)>

In [20]:
# Typecasting a Tensor
tensor3 = tf.constant([[4.6,4.2],
                       [7.5,3.6],
                       [6.7,8.3]], dtype=tf.float32)

tensor_as_int = tf.cast(tensor3, tf.int32)

print(tensor3)
print(tensor_as_int)

tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [6.7 8.3]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[4 4]
 [7 3]
 [6 8]], shape=(3, 2), dtype=int32)


In [23]:
# Tranforming a Tensor
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 7, 6],
       [4, 3, 8]])>

In [25]:
# Matrix multiplication of Tensor

C = tf.constant([[5, 8], [3, 9]])
D = tf.constant([[4], [2]])

CD = tf.matmul(C, D)
CD

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]])>

In [27]:
# Elementwise multiplication
CD = tf.multiply(C, D)
CD

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]])>

In [28]:
# Identity Matrix

E = tf.constant([[4, 9], [5, 6], [1, 8]])

rows, columns = E.shape

In [29]:
rows

3

In [30]:
columns

2

In [32]:
# Crating an Identity Matrix

E_identity = tf.eye(num_rows= rows, num_columns = columns, dtype=tf.int32)
E_identity

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]])>